import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	// utilitiesSidebar: [{ type: 'autogenerated', dirName: '.' }],
	overviewSidebar: [
		{
			type: 'doc',
			id: 'intro',
		},
	],
	utilitiesSidebar: [
		{
			type: 'category',
			label: 'String Utilities',
			link: {
				type: 'doc',
				id: 'string/intro-string',
			},
			items: [
				'string/generateRandomID',
				'string/generateAnagrams',
				'string/capitalizeString',
				'string/convertStringCase',
				'string/truncateString',
				'string/trimString',
				'string/replaceAllInString',
			],
		},
		{
			type: 'category',
			label: 'Array Utilities',
			link: {
				type: 'doc',
				id: 'array/intro-array',
			},
			items: [
				'array/sortAnArray',
				'array/createOptionsArray',
				'array/getDuplicates',
				'array/removeDuplicates',
				'array/findMissingElements',
				'array/flattenArray',
				'array/filterArrayOfObjects',
				'array/getLastArrayElement',
				'array/splitArray',
				'array/shuffleArray',
				'array/naturalSort',
				'array/moveArrayElement',
				'array/rotateArray',
			],
		},
	],
	classesSidebar: [
		{
			type: 'category',
			label: 'Classes',
			link: {
				type: 'doc',
				id: 'classes/intro-classes',
			},
			items: [
				'classes/Chronos',
				// 'classes/finder',
				// add more class docs here
			],
		},
	],

	predicatesSidebar: [
		{
			type: 'category',
			label: 'Predicate Functions',
			link: {
				type: 'doc',
				id: 'predicates/intro-predicates',
			},
			items: ['predicates/isInvalidOrEmptyArray'],
		},
		{
			type: 'category',
			label: 'Type Guards',
			link: {
				type: 'doc',
				id: 'guards/intro-guards',
			},
			items: [
				// 'guards/isNumber',
				// 'guards/isBoolean',
				// 'guards/isObject',
				// 'guards/isArray',
				// 'guards/isFunction',
				// 'guards/isDate',
				// 'guards/isNullOrUndefined',
				// 'guards/isValidEmail',
				// 'guards/isValidPhoneNumber',
			],
		},
	],
};

export default sidebars;
